### ISSUE TITLE
Example fails to compile

### ISSUE THREAD

**Issue by sgsullivan** [rgamba/evtwebsocket#1]
Using go version 1.6 (at least) the examples here do not seem to compile. For example, when I try to run `examples/client.go` , I just get this:

> cannot use func literal (type func(_"golang.org/x/net/websocket".Conn)) as type
> func(_"github.com/rgamba/evtwebsocket/vendor/golang.org/x/net/websocket".Conn) in field value

**Comment by rgamba** [comment]
Solved. Thanks to @jeffallen

**Comment by derrickb** [comment]
This isn't fixed for me... I just pulled this down today and none of the examples work.  I'm getting the same error as @sgsullivan 

I tried copying/pasting the README example and using the client.go example file.

Edit: Deleting the vendor folder fixes it.

**Comment by jeffallen** [comment]
I agree that the vendor folder should go. Libraries shoud not vendor dependencies, only things in package main.

**Comment by rgamba** [comment]
Agreed. Vendor folder was deleted.
